name: Fetch arXiv Metadata

on:
  issues:
    types: [opened, reopened]

jobs:
  fetch-arxiv-metadata:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'stored-object')
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install gh-store-client
        run: npm install gh-store-client
        
      - name: Fetch and post arXiv metadata
        uses: actions/github-script@v7
        with:
          script: |
            
            function findObjectId(labels) {
              if (!labels || !Array.isArray(labels)) {
                return null;
              }
              
              for (const label of labels) {
                if (label.name && label.name.startsWith('UID:')) {
                  return label.name.substring(4).trim();
                }
              }
              
              return null;
            }
            
            function removePrefix(string, prefix, sep = ':') {
              if (string.startsWith(prefix + sep)) {
                return string.slice(prefix.length + sep.length);
              }
              return null; // Return null to indicate no match
            }
            
            function extractPaperId(string, prefix) {
              // Case 1: Format is "prefix:id"
              let result = removePrefix(string, prefix, ':');
              if (result !== null) return result;
              
              // Case 2: Format is "prefix.id"
              result = removePrefix(string, prefix, '.');
              if (result !== null) return result;
              
              // Case 3: Format is "prefix:prefix:id"
              result = removePrefix(string, prefix + ':' + prefix, ':');
              if (result !== null) return result;
              
              // Case 3 alternate: Format is "prefix.prefix.id"
              result = removePrefix(string, prefix + '.' + prefix, '.');
              if (result !== null) return result;
              
              // Case 4: If none of the above, return the original string
              return string;
            }

            ///////////////////////////////////////////////////////////

            const issue = context.payload.issue;
            const issueNumber = issue.number;
            const issueBody = issue.body.trim();            
            console.log(`Processing issue #${issueNumber} with body: ${issueBody}`);

            const objectId = findObjectId(issue.labels);            
            if (!objectId) {
              throw new Error(`Unable to identify a gh-store UID among labels: ${issue.labels}`);
            }
            console.log(`Found objectId: ${objectId}`);

            if (!objectId.startsWith('paper:')) {
              throw new Error(`Exiting: ${objectId} is not a paper.`);
            }
            const paperId = objectId.slice(6);
            const arxivId = extractPaperId(paperId, 'arxiv');

            // Validate arXiv ID format (basic validation)
            const arxivIdRegex = /\d{4}\.\d{4,5}(v\d+)?|\w+\/\d{7}(v\d+)?/;
            if (!arxivIdRegex.test(arxivId)) {
              throw new Error(`Invalid arXiv ID format: ${arxivId}`);
            }
            
            //let store = GitHubStoreClient(token=${{ secrets.GITHUB_TOKEN }}, repo=${{ github.repository }});
            const { GitHubStoreClient } = require('gh-store-client');
            const store = new GitHubStoreClient(
              process.env.GITHUB_TOKEN,
              `${context.repo.owner}/${context.repo.repo}`
            );
            let obj = store.getObject(objectId);
            console.log("Got stored object:", obj);
            
            console.log(`Fetching metadata for arXiv ID: ${arxivId}`);
            
            try {
              // Fetch metadata from arXiv API using native fetch
              const response = await fetch(`http://export.arxiv.org/api/query?id_list=${arxivId}`);
              
              if (!response.ok) {
                throw new Error(`arXiv API responded with status: ${response.status}`);
              }
              
              const xmlData = await response.text();
              
              // Parse XML response using DOMParser
              const parseXML = (xmlString) => {
                // Simple XML parser for arXiv API response
                // This extracts specific elements we need
                const getTagContent = (tag, xml) => {
                  const regex = new RegExp(`<${tag}[^>]*>(.*?)</${tag}>`, 'gs');
                  const matches = [...xml.matchAll(regex)];
                  return matches.map(m => m[1].trim());
                };
                
                const getAttributes = (tag, xml) => {
                  const regex = new RegExp(`<${tag}([^>]*)>`, 'g');
                  const matches = [...xml.matchAll(regex)];
                  return matches.map(m => {
                    const attrs = {};
                    const attrMatches = [...m[1].matchAll(/(\w+)="([^"]*)"/g)];
                    attrMatches.forEach(attr => {
                      attrs[attr[1]] = attr[2];
                    });
                    return attrs;
                  });
                };
                
                const authors = getTagContent('author', xmlString).map(author => {
                  const name = getTagContent('name', author)[0];
                  return name;
                });
                
                const categories = getAttributes('category', xmlString).map(attr => attr.term);
                
                const links = getAttributes('link', xmlString).map(attr => ({
                  rel: attr.rel,
                  href: attr.href,
                  type: attr.type
                }));
                
                return {
                  id: getTagContent('id', xmlString)[0],
                  title: getTagContent('title', xmlString)[0],
                  authors: authors,
                  published: getTagContent('published', xmlString)[0],
                  updated: getTagContent('updated', xmlString)[0],
                  summary: getTagContent('summary', xmlString)[0],
                  categories: categories,
                  links: links
                };
              };
              
              // Extract relevant metadata
              const metadata = parseXML(xmlData);
              
              if (!metadata.id) {
                throw new Error(`No metadata found for arXiv ID: ${arxivId}`);
              }
              
              console.log(`Successfully fetched metadata for arXiv ID: ${arxivId}`);
              
              // Post metadata as comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `\`\`\`json\n${JSON.stringify(metadata, null, 2)}\n\`\`\``
              });
              
              console.log('Posted metadata comment to issue');
              
            } catch (error) {
              console.error(`Error: ${error.message}`);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `Error fetching arXiv metadata: ${error.message}`
              });
            }
