name: 1) Process Updates + Enrichments

on:
  workflow_dispatch:
  issues:
    types: [reopened]
    
  schedule:
    - cron: '0 0 * * *'

jobs:
  hydrate-arxiv:
    runs-on: ubuntu-latest
    if: >
      contains(join(github.event.issue.labels.*.name, ','), 'TODO:hydrate-metadata') ||
      github.event_name == 'workflow_dispatch'
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: pip install gh-store>=0.11.2 arxiv

      - name: Process Updates
        run: |
          python scripts/hydrate_metadata.py \
            hydrate_all_open_issues \
            --repo ${{ github.repository }} \
            --token ${{ secrets.GITHUB_TOKEN }}

  process-updates:
    runs-on: ubuntu-latest
    if: "!contains(github.event.issue.labels.*.name, 'TODO:hydrate-metadata') && contains(github.event.issue.labels.*.name, 'stored-object')"
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: pip install gh-store>=0.11.2
          
      - name: Process Updates
        run: |
          python -m gh_store process-updates \
            --issue ${{ github.event.issue.number }} \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --repo ${{ github.repository }}

  notify-deploy-after-process:
    needs: [process-updates]
    if: contains(join(github.event.issue.labels.*.name, ','), 'stored-object')
    runs-on: ubuntu-latest
    steps:
          
      - name: Trigger frontend deploy
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/2_deploy-frontend.yml/dispatches \
            -d "{\"ref\":\"${{ github.ref }}\"}"

  notify-deploy-after-enrichment:
    needs: [hydrate-arxiv]
    if: contains(join(github.event.issue.labels.*.name, ','), 'stored-object')
    runs-on: ubuntu-latest
    steps:
          
      - name: Trigger frontend deploy
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/2_deploy-frontend.yml/dispatches \
            -d "{\"ref\":\"${{ github.ref }}\"}"
